<template>
  <q-page class="flex flex-center column">
    <q-item-label header>Users</q-item-label>
    <q-list
      v-model="users"
      :key="user.uid"
      v-for="(user, index) in users.data"
      class="rounded-borders"
      style="width: 600px;">

      <q-item>
        <q-item-section top class="col-2 gt-sm">
          <q-item-label class="q-mt-sm">user {{ index + 1 }}</q-item-label>
        </q-item-section>

        <q-item-section top>
          <q-item-label lines="1">
            <span class="text-weight-medium">
              full name: {{ user.name }} {{ user.surname }}
            </span>
            <span class="text-grey-8"> - Free account</span>
          </q-item-label>
          <q-item-label caption lines="1">
            #{{ user.uid }}: Generated by Cucumber Group
          </q-item-label>
        </q-item-section>

        <q-item-section top side>
          <div class="text-grey-8 q-gutter-xs">
            <q-btn
              @click="onDelete(user.uid)"
              class="gt-xs"
              size="12px"
              flat
              dense
              round
              icon="delete" />
            <q-btn
              class="gt-xs"
              size="12px"
              flat
              dense
              round
              icon="edit"
              @click="openPopup(user)"/>
          </div>
        </q-item-section>

      </q-item>

      <q-separator spaced />
    </q-list>
    <q-btn @click="onPopupForNewUser" color="white" text-color="black" label="ADD NEW USER" />

    <div
      v-if="popup.open"
      class="absolute-center q-gutter-md"
      style="
        width: 300px;
        z-index: 19;
        background-color: white;
        border-radius: 5%;
        padding: 10px;">
      <q-input rounded outlined v-model="popup.name" label="Name" />
      <q-input rounded outlined v-model="popup.surname" label="Surname" />
      <q-input v-if="popup.forNewUser" rounded outlined v-model="popup.email" label="Email" />
      <q-input v-if="popup.forNewUser" rounded outlined v-model="popup.password" label="Password" />
      <div class="flex flex-center justify-between">
        <q-btn @click="closePopup" color="red" icon="block" />
        <q-btn @click="onPopupAction" color="primary" icon="send" />
      </div>
    </div>

    <div
      v-if="popup.open"
      class="absolute-center dimmed"
      style="z-index: 9; width: 100%; height: 100%;"
    ></div>
  </q-page>
</template>

<script>
import { useUsersStore } from 'src/stores/users';

export default {
  name: 'UsersPage',
  setup() {
    const users = useUsersStore();

    return {
      users,
    };
  },
  data() {
    return {
      popup: {
        open: false,
        forNewUser: false,
        name: '',
        surname: '',
        uid: '',
        email: '',
        password: '',
      },
    };
  },
  methods: {
    openPopup(user) {
      this.popup.name = user.name;
      this.popup.surname = user.surname;
      this.popup.uid = user.uid;
      this.popup.open = true;
    },
    closePopup() {
      this.popup.open = false;
      this.popup.forNewUser = false;
      this.popup.name = '';
      this.popup.surname = '';
      this.popup.uid = '';
      this.popup.email = '';
      this.popup.password = '';
    },
    onPopupAction() {
      if (this.popup.forNewUser) {
        this.users.create(
          this.popup.email,
          this.popup.password,
          this.popup.name,
          this.popup.surname,
        );
        this.closePopup();
      } else if (this.popup.name && this.popup.surname) {
        this.popup.open = false;
        this.users.update(this.popup.uid, {
          name: this.popup.name,
          surname: this.popup.surname,
        });
        this.closePopup();
      }
    },
    onPopupForNewUser() {
      this.popup.forNewUser = true;
      this.popup.open = true;
    },
    onDelete(uid) {
      this.users.delete(uid);
    },
  },
};
</script>
